--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


--# inherit Hello;
package PolyORB_HI_Generated.Subprograms is

  procedure Hello_Spg_1;

  procedure Hello_Spg_2;

  procedure Hello_Spg_3;

end PolyORB_HI_Generated.Subprograms;
