--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Subprograms;

package body PolyORB_HI_Generated.Activity is

  --  Periodic task : Task1

  ---------------
  -- Task1_Job -- 
  ---------------

  function Task1_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.Hello_Spg_1;
    --  Return error code
    return Error_Ü;
  end Task1_Job;

  --  Periodic task : Task2

  ---------------
  -- Task2_Job -- 
  ---------------

  function Task2_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.Hello_Spg_2;
    --  Return error code
    return Error_Ü;
  end Task2_Job;

  --  Periodic task : Task3

  ---------------
  -- Task3_Job -- 
  ---------------

  function Task3_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.Hello_Spg_3;
    --  Return error code
    return Error_Ü;
  end Task3_Job;

end PolyORB_HI_Generated.Activity;
