--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with System;
with PolyORB_HI.Periodic_Task;

--# inherit PolyORB_HI.Errors,
--#         PolyORB_HI_Generated.Deployment,
--#         Ada.Real_Time,
--#         System,
--#         PolyORB_HI.Periodic_Task,
--#         PolyORB_HI_Generated.Subprograms;
package PolyORB_HI_Generated.Activity is

  --  Periodic task : Task1

  function Task1_Job return PolyORB_HI.Errors.Error_Kind;

  package Task1_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.node_a_Task1_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1000),
      Task_Priority => System.Default_Priority,
      Task_Stack_Size => 100000,
      Job => Task1_Job);

  --  Periodic task : Task2

  function Task2_Job return PolyORB_HI.Errors.Error_Kind;

  package Task2_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.node_a_Task2_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1500),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1500),
      Task_Priority => System.Default_Priority,
      Task_Stack_Size => 100000,
      Job => Task2_Job);

  --  Periodic task : Task3

  function Task3_Job return PolyORB_HI.Errors.Error_Kind;

  package Task3_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.node_a_Task3_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (3600),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (3600),
      Task_Priority => System.Default_Priority,
      Task_Stack_Size => 100000,
      Job => Task3_Job);

end PolyORB_HI_Generated.Activity;
